version: "3.8"

services:
  app-dev:
    container_name: app-dev
    image: marclopezavila/app-dev
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - "${PORT}:8080"
  app-pro:
    container_name: app-prod
    image: marclopezavila/app-prod
    build:
      context: .
      target: production
    ports:
      - "${PORT}:80"
