version: "3.8"

services:
  app-dev:
    container_name: app-dev
    image: app-dev
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - "3000:8080"
  app-pro:
    container_name: app-prod
    image: app-prod
    build:
      context: .
      target: production
    ports:
      - "3000:80"
